config/routes.rb
Rails.application.routes.draw do

  namespace :hogehoge do
    get 'test_admin/new'
  end
  namespace :hoge do
    get 'test_admin/new'
  end
  devise_for :customers, skip: :all
  devise_scope :customer do
    get "/customers/sign_up" => "public/devise/registrations#new"
    post "/customers" => "public/devise/registrations#create"
    # get "/customers/sign_in" => "public/devise/sessions#new",as: "new_session"
    get "/customers/sign_in" => "public/devise/sessions#new"
    post "/customers/sign_in" => "public/devise/sessions#create"
    delete "/customers/sign_out" => "public/devise/sessions#destroy"
  end

  scope module: :public do
    get "top" => "homes#top",as: "top"
    # scope module: :devise do
    #   devise_for :customers
    # end
    get '/' => 'homes#top'
    get 'about' => 'homes#about'
    resources :items, only:[:index, :show]
    patch 'withdrawal_update' => 'customers#withdraw'
    get "customers" => "customers#my_page",as: "my_page"
    resources :customers, only:[:edit, :update]
    get 'withdrawal' => 'customers#unsubscribe'
    delete 'cart_items' => 'cart_items#destroy_all'
    resources :cart_items, only:[:index, :destroy, :update, :create, :destroy_all]
    resources :orders, only:[:new, :edit, :index, :show, :create]
    post 'oders_confirm' => 'orders#confirm'
    get 'oders_complete' => 'orders#complete'
    resources :deliverys, only:[:index, :edit, :create, :update, :destroy]

  end

  devise_for :admins
  devise_scope :admin do
    get 'admin/sign_in'=> "devise/sessions#new"
  end

  namespace :admin do
    get '/' => "homes#top"
    resources :items, only:[:index, :new, :create, :show, :edit, :update]
    get 'orders/:id' => "orders#show",as: 'orders'
    patch 'orders/update'
    resources :genres, only:[:index, :create, :edit, :update]
    resources :customers, only:[:index, :show, :edit, :update]
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :cart_items, dependent: :destroy
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :item
  belongs_to :customer
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :cart_items
  has_many :orders
  has_many :addresses
  enum is_active:{
    "有効" => true, "退会" => false
  }
  def active_for_authentication?
    super && (self.is_active ==  "有効" )
  end
end

app/models/genre.rb
class Genre < ApplicationRecord
end

app/models/item.rb
class Item < ApplicationRecord
  attachment :image
  has_many :cart_items
  has_many :order_items
end

app/models/order.rb
class Order < ApplicationRecord
    enum payment_method:{
        クレジットカード: 0, 銀行振込: 1
    }
    belongs_to :customer
    has_many :order_items
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :item
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @order_items = OrderItem.all
  end

  def about
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  def index
    @items = Item.all
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    @item.save
    redirect_to admin_item_path(@item.id)
  end

  def show
    @item = Item.find(params[:id])
    @items = Item.all
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    @item.update(item_params)
    redirect_to admin_item_path(@item.id)
  end

  private
  def item_params
    params.require(:item).permit(:genre_id, :name, :image, :caption, :price,
    :created_at, :updated_at, :introduction)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameter, if: :devise_controller?

  def after_sign_in_path_for(resource)
    case resource
    when Customer
      items_path
    when Admin
      admin_path
    end
  end

  def after_sign_out_path_for(resource)
    case resource
    when :customer
      customers_sign_in_path
    when :admin
      admin_sign_in_path
    end
  end


  protected
  def configure_permitted_parameter
    devise_parameter_sanitizer.permit(:sign_up,
    keys: [:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number, :email])
  end

  private
  def current_cart
    current_cart = Cart.find_by(id: session[:cart_id])
    current_cart = Cart.create unless current_cart
    session[:cart_id] = current_cart.id
    current_cart
  end

end

app/helpers/admin/admin_helper.rb
module Admin::AdminHelper
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/devise_helper.rb
module Admin::DeviseHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hoge/test_admin_helper.rb
module Hoge::TestAdminHelper
end

app/helpers/hogehoge/test_admin_helper.rb
module Hogehoge::TestAdminHelper
end

app/views/admin/items/create.html.erb
<h1>Admin::Items#create</h1>
<p>Find me in app/views/admin/items/create.html.erb</p>

app/views/admin/items/edit.html.erb
<h1>商品編集</h1>
<%= form_with model: [:admin,@item], local:true do |f| %>
<table>
  <tr>
    <th>商品画像</th>
    <th><%= f.attachment_field :image %></th>
  </tr>
  <tr>
    <th>商品名</th>
    <th><%= f.text_field :name %></th>
  </tr>
  <tr>
    <th>商品説明文</th>
    <th><%= f.text_area :introduction %></th>
  </tr>
  <tr>
    <th>ジャンル</th>
    <th><%= f.text_field :genre_id %></th>
  </tr>
  <tr>
    <th>税込価格</th></br>
    <th><%= f.text_field :price, data: { autonumeric: true } %>円</th>
  </tr>
  <tr>
    <th>販売ステータス</th>
    <th></th>
  </tr>
</table><br>
<%= f.submit '変更を保存' %>
<% end %>

app/views/admin/items/index.html.erb
<h1>商品一覧</h1>
<span><%= link_to "+", new_admin_item_path %></span>
<% @items.each do |item| %>
<table>
  <tr>
    <th>商品ID</th>
    <th>商品名</th>
    <th>税抜価格</th>
    <th>ジャンル</th>
    <th>ステータス</th>
  </tr>
  <tr>
    <th><%= item.id %></th>
    <th><%= link_to item.name, admin_item_path(item.id) %></th>
    <th><%= item.price %></th>
    <th><%= "ジャンル" %></th>
    <th><%= "ステータス" %></th>
  </tr>
</table></br>
<% end %>

app/views/admin/items/new.html.erb
<h1>商品新規登録画面</h1>
<%= form_with model: [:admin,@item], url: admin_items_path, local:true do |f| %>
<table>
  <tr>
    <th>商品画像</th>
    <th><%= f.attachment_field :image %></th>
  </tr>
  <tr>
    <th>商品名</th>
    <th><%= f.text_field :name %></th>
  </tr>
  <tr>
    <th>商品説明文</th>
    <th><%= f.text_area :introduction %></th>
  </tr>
  <tr>
    <th>ジャンル</th>
    <th><%= f.text_field :genre_id %></th>
  </tr>
  <tr>
    <th>税抜き価格</th>
    <th><%= f.text_field :price, data: { autonumeric: true } %>円</th>
  </tr>
  <tr>
    <th>販売ステータス</th>
    <th></th>
  </tr>
</table><br>
<%= f.submit '新規登録' %>
<% end %>

app/views/admin/items/show.html.erb
<h1>商品詳細</h1>
<table>
  <tr>
    <tb><%= attachment_image_tag @item, :image %></tb>
  </tr></br>
  <tr>
    <tb>商品名  </tb>
    <tb><%= @item.name %></tb>
  </tr></br>
  <tr>
    <tb>商品説明  </tb>
    <tb><%= @item.introduction %></tb>
  </tr></br>
  <tr>
    <tb>ジャンル</tb>
    <tb></tb>
  </tr></br>
  <tr>
    <tb>税込価格</tb></br>
    <tb>(税抜価格)  </tb>
    <tb>
      <%= (@item.price * 1.1).round %>
      (<%= @item.price %>)円
    </tb>
  </tr></br>
  <tr>
    <tb>販売ステータス  </tb>
    <tb></tb>
  </tr>
  </br>
  </br>
  <span><%= link_to "編集する", edit_admin_item_path(@item.id) %></span>
</table>

app/views/admin/items/update.html.erb
<h1>Admin::Items#update</h1>
<p>Find me in app/views/admin/items/update.html.erb</p>