config/routes.rb
Rails.application.routes.draw do

  namespace :hogehoge do
    get 'test_admin/new'
  end
  namespace :hoge do
    get 'test_admin/new'
  end
  devise_for :customers, skip: :all
  devise_scope :customer do
    get "/customers/sign_up" => "public/devise/registrations#new"
    post "/customers" => "public/devise/registrations#create"
    # get "/customers/sign_in" => "public/devise/sessions#new",as: "new_session"
    get "/customers/sign_in" => "public/devise/sessions#new"
    post "/customers/sign_in" => "public/devise/sessions#create"
    delete "/customers/sign_out" => "public/devise/sessions#destroy"
  end

  scope module: :public do
    get "top" => "homes#top",as: "top"
    # scope module: :devise do
    #   devise_for :customers
    # end
    get '/' => 'homes#top'
    get 'about' => 'homes#about'
    resources :items, only:[:index, :show]
    patch 'withdrawal_update' => 'customers#withdraw'
    get "customers" => "customers#my_page",as: "my_page"
    resources :customers, only:[:edit, :update]
    get 'withdrawal' => 'customers#unsubscribe'
    delete 'cart_items' => 'cart_items#destroy_all'
    resources :cart_items, only:[:index, :destroy, :update, :create, :destroy_all]
    resources :orders, only:[:new, :edit, :index, :show, :create]
    post 'oders_confirm' => 'orders#confirm'
    get 'oders_complete' => 'orders#complete'
    resources :deliverys, only:[:index, :edit, :create, :update, :destroy]

  end

  devise_for :admins
  devise_scope :admin do
    get 'admin/sign_in'=> "devise/sessions#new"
  end

  namespace :admin do
    get '/' => "homes#top"
    resources :items, only:[:index, :new, :create, :show, :edit, :update]
    get 'orders/:id' => "orders#show",as: 'orders'
    patch 'orders/update'
    resources :genres, only:[:index, :create, :edit, :update]
    resources :customers, only:[:index, :show, :edit, :update]
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :cart_items, dependent: :destroy
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :item
  belongs_to :customer
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :cart_items
  has_many :orders
  has_many :addresses
  enum is_active:{
    "有効" => true, "退会" => false
  }
  def active_for_authentication?
    super && (self.is_active ==  "有効" )
  end
end

app/models/genre.rb
class Genre < ApplicationRecord
end

app/models/item.rb
class Item < ApplicationRecord
  attachment :image
  has_many :cart_items
  has_many :order_items
end

app/models/order.rb
class Order < ApplicationRecord
    enum payment_method:{
        クレジットカード: 0, 銀行振込: 1
    }
    belongs_to :customer
    has_many :order_items
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :item
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  def index
    @customers = Customer.all
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer =  Customer.find(params[:id])
    @customer.update(customer_params)
    redirect_to admin_customer_path
  end

  private
  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana,
    :postal_code, :address, :telephone_number, :email)
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @order_items = OrderItem.all
  end

  def about
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  def index
    @items = Item.all
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    @item.save
    redirect_to admin_item_path(@item.id)
  end

  def show
    @item = Item.find(params[:id])
    @items = Item.all
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    @item.update(item_params)
    redirect_to admin_item_path(@item.id)
  end

  private
  def item_params
    params.require(:item).permit(:genre_id, :name, :image, :caption, :price,
    :created_at, :updated_at, :introduction)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameter, if: :devise_controller?

  def after_sign_in_path_for(resource)
    case resource
    when Customer
      items_path
    when Admin
      admin_path
    end
  end

  def after_sign_out_path_for(resource)
    case resource
    when :customer
      customers_sign_in_path
    when :admin
      admin_sign_in_path
    end
  end


  protected
  def configure_permitted_parameter
    devise_parameter_sanitizer.permit(:sign_up,
    keys: [:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number, :email])
  end

  private
  def current_cart
    current_cart = Cart.find_by(id: session[:cart_id])
    current_cart = Cart.create unless current_cart
    session[:cart_id] = current_cart.id
    current_cart
  end

end

app/helpers/admin/admin_helper.rb
module Admin::AdminHelper
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/devise_helper.rb
module Admin::DeviseHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hoge/test_admin_helper.rb
module Hoge::TestAdminHelper
end

app/views/admin/customers/edit.html.erb
<h1><%= @customer.last_name + @customer.first_name %>さんの会員情報編集</h1>
<table>
  <tr>
    <tb>会員ID</tb>
    <tb><%= @customer.id %></tb>
  </tr>
</table>
<%= form_with model:@customer, url: admin_customer_path, local:true do |f| %>
  <table>
    <tr>
      <tb>氏名</tb>
      <tb><%= f.text_field :last_name %></tb>
      <tb><%= f.text_field :first_name %></tb>
    </tr>
    </br>
    <tr>
      <tb>フリガナ</tb>
      <tb><%= f.text_field :last_name_kana %></tb>
      <tb><%= f.text_field :first_name_kana %></tb>
    </tr>
    </br>
    <tr>
      <tb>郵便番号</tb>
      <tb><%= f.text_field :postal_code %></tb>
    </tr>
    </br>
    <tr>
      <tb>住所</tb>
      <tb><%= f.text_field :address %></tb>
    </tr>
    </br>
    <tr>
      <tb>電話番号</tb>
      <tb><%= f.text_field :telephone_number %></tb>
    </tr>
    </br>
    <tr>
      <tb>メールアドレス</tb>
      <tb><%= f.text_field :email %></tb>
    </tr>
    </br>
    <tr>
      <tb>会員ステータス</tb>
      <%= form_with model:@customer, local:true do |f| %>
      <td>
        <%= f.radio_button :is_active, "有効" %>
        <%= f.label :is_active, "有効" %>
      </td>
      <td>
        <%= f.radio_button :is_active, "退会" %>
        <%= f.label :is_active, "退会" %>
      </td>
      <% end %>
    </tr>
  </table>
  <%= f.submit "編集を保存" %>
<% end %>

app/views/admin/customers/index.html.erb
<h1>会員一覧</h1>
<table width="300" >
  <tr>
    <th>会員ID</th>
    <th>氏名</th>
    <th>メールアドレス</th>
    <th>スターテス</th>
  </tr>
</table>
<% @customers.each do |f| %>
<table width="200" >
  <tr>
    <tb ><%= f.id %></tb>
    <tb><%= link_to f.last_name + f.first_name, admin_customer_path(f.id) %></tb>
    <tb><%= f.email %></tb>
    <tb><%= f.is_active %></tb>
  </tr></br>
</table>
<% end %>

app/views/admin/customers/show.html.erb
<h1><%= @customer.last_name + @customer.first_name %>の会員詳細</h1>

<table>
  <tr>
    <th>会員ID</th>
    <td><%= @customer.id %></td>
  </tr>
  <tr>
    <th>氏名</th>
    <td><%= @customer.last_name + @customer.first_name %></td>
  </tr>
  <tr>
    <th>フリガナ</th>
    <td><%= @customer.last_name_kana + @customer.first_name_kana %></td>
  </tr>
  <tr>
    <th>郵便番号</th>
    <td><%= @customer.postal_code %></td>
  </tr>
  <tr>
    <th>住所</th>
    <td><%= @customer.address %></td>
  </tr>
  <tr>
    <th>電話番号</th>
    <td><%= @customer.telephone_number %></td>
  </tr>
  <tr>
    <th>メールアドレス</th>
    <td><%= @customer.email %></td>
  </tr>
  <tr>
    <th>会員ステータス</th>
    <td><%= @customer.is_active %></td>
  </tr>
</table>
<%= link_to "編集する", edit_admin_customer_path(@customer.id) %>
<%= link_to "注文履歴一覧を見る", edit_admin_customer_path(@customer.id) %>

app/views/admin/customers/update.html.erb
<h1>Admin::Customers#update</h1>
<p>Find me in app/views/admin/customers/update.html.erb</p>