config/routes.rb
Rails.application.routes.draw do

  namespace :hogehoge do
    get 'test_admin/new'
  end
  namespace :hoge do
    get 'test_admin/new'
  end
  devise_for :customers, skip: :all
  devise_scope :customer do
    get "/customers/sign_up" => "public/devise/registrations#new"
    post "/customers" => "public/devise/registrations#create"
    # get "/customers/sign_in" => "public/devise/sessions#new",as: "new_session"
    get "/customers/sign_in" => "public/devise/sessions#new"
    post "/customers/sign_in" => "public/devise/sessions#create"
    delete "/customers/sign_out" => "public/devise/sessions#destroy"
  end

  scope module: :public do
    get "top" => "homes#top",as: "top"
    # scope module: :devise do
    #   devise_for :customers
    # end
    get '/' => 'homes#top'
    get 'about' => 'homes#about'
    resources :items, only:[:index, :show]
    patch 'withdrawal_update' => 'customers#withdraw'
    get "customers" => "customers#my_page",as: "my_page"
    resources :customers, only:[:edit, :update]
    get 'withdrawal' => 'customers#unsubscribe'
    delete 'cart_items' => 'cart_items#destroy_all'
    resources :cart_items, only:[:index, :destroy, :update, :create, :destroy_all]
    resources :orders, only:[:new, :edit, :index, :show, :create]
    post 'oders_confirm' => 'orders#confirm'
    get 'oders_complete' => 'orders#complete'
    resources :deliverys, only:[:index, :edit, :create, :update, :destroy]

  end

  devise_for :admins
  devise_scope :admin do
    get 'admin/sign_in'=> "devise/sessions#new"
  end

  namespace :admin do
    get '/' => "homes#top"
    resources :items, only:[:index, :new, :create, :show, :edit, :update]
    get 'orders/:id' => "orders#show",as: 'orders'
    patch 'orders/update'
    resources :genres, only:[:index, :create, :edit, :update]
    resources :customers, only:[:index, :show, :edit, :update]
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :cart_items, dependent: :destroy
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :item
  belongs_to :customer
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :cart_items
  has_many :orders
  has_many :addresses
  enum is_active:{
    "有効" => true, "退会" => false
  }
  def active_for_authentication?
    super && (self.is_active ==  "有効" )
  end
end

app/models/genre.rb
class Genre < ApplicationRecord
end

app/models/item.rb
class Item < ApplicationRecord
  attachment :image
  has_many :cart_items
  has_many :order_items
end

app/models/order.rb
class Order < ApplicationRecord
    enum payment_method:{
        クレジットカード: 0, 銀行振込: 1
    }
    belongs_to :customer
    has_many :order_items
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :item
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameter, if: :devise_controller?

  def after_sign_in_path_for(resource)
    case resource
    when Customer
      items_path
    when Admin
      admin_path
    end
  end

  def after_sign_out_path_for(resource)
    case resource
    when :customer
      customers_sign_in_path
    when :admin
      admin_sign_in_path
    end
  end


  protected
  def configure_permitted_parameter
    devise_parameter_sanitizer.permit(:sign_up,
    keys: [:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number, :email])
  end

  private
  def current_cart
    current_cart = Cart.find_by(id: session[:cart_id])
    current_cart = Cart.create unless current_cart
    session[:cart_id] = current_cart.id
    current_cart
  end

end

app/helpers/admin/admin_helper.rb
module Admin::AdminHelper
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/devise_helper.rb
module Admin::DeviseHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hoge/test_admin_helper.rb
module Hoge::TestAdminHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if customer_signed_in? %>
      <li><%= link_to "LOGO", items_path %></li>
      <li><%= link_to "マイページ", my_page_path %></li>
      <li><%= link_to "商品一覧", items_path %></li>
      <li><%= link_to "カート", orders_path %></li>
      <li><%= link_to "ログアウト", customers_sign_out_path,method: :delete %></li>
    <% elsif admin_signed_in? %>
      <li><%= link_to "LOGO", admin_items_path %></li>
      <li><%= link_to "商品一覧", admin_items_path %></li>
      <li><%= link_to "会員一覧", admin_customers_path %></li>
      <li><%= link_to "注文履歴一覧", admin_path %></li>
      <li><%= link_to "ジャンル一覧", admin_genres_path %></li>
      <li><%= link_to "ログアウト", destroy_admin_session_path,method: :delete %></li>
    <% else %>
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "商品一覧", items_path %></li>
      <li><%= link_to "新規登録", customers_sign_up_path %></li>
      <li><%= link_to "ログイン", customers_sign_in_path %></li>
    <% end %>
    <%= yield %>
  </body>
</html>